# Generated by Django 5.0.14 on 2025-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_contact',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_class',
            field=models.CharField(max_length=20),
        ),
    ]
