# Generated by Django 5.2 on 2025-08-17 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_student_parent_contact_student_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(max_length=255)),
                ('sub_strand', models.CharField(max_length=255)),
                ('general_outcome', models.TextField()),
                ('specific_outcome1', models.TextField()),
                ('specific_outcome2', models.TextField()),
                ('specific_outcome3', models.TextField()),
                ('enquiry_question', models.TextField()),
                ('introduction', models.TextField()),
                ('lesson_development', models.TextField()),
                ('conclusion', models.TextField()),
                ('reflection', models.TextField()),
                ('assignment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
