# Generated by Django 5.2 on 2025-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lessonplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='specific_outcome2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='specific_outcome3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
