# Generated by Django 5.2 on 2025-08-17 20:45

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lessonplan_specific_outcome2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lessons.lessonplan'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='assignment',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
